### ISSUE TITLE
Calling Python function from C++

### ISSUE THREAD

**Issue by tfgsupport** [boostorg/python#102]
Hi,

Please can you help explain how a user defined C++ class instance can be passed as an argument to a Python function. I am able to pass an integer argument using the PyInt_FromLong function as below.

```
	int MyClass::getSquare( int x )
	{
		return pow( x, 2 );
	}
	BOOST_PYTHON_MODULE( Test )
	{
		class_<MyClass>( "MyClass" )
			.def( "getSquare", &MyClass::getSquare )
			;
	}

	PyObject * py_args_tuple = PyTuple_New(1);
	PyObject * py_int;
	py_int = PyInt_FromLong( 4 );
	PyTuple_SetItem( py_args_tuple, 0, py_int );
	PyObject_CallObject( pFun, py_args_tuple );

        def getSquare( x ):
                        // Create MyClass object myClass
			print myClass.getSquare(4)

```
Thanks,

Nilufar

**Comment by stefanseefeld** [comment]
Have you tried the examples in the Boost.Python tutorial ? The automatic conversion from C++ objects to the appropriate Python wrapper object is done when the Boost.Python call operator is invoked. That is, for this to work you shouldn't use the Python C API but really Boost.Python.
Assuming you hold the function in a Boost.Python object `pFun`, you can simply call that with the class instance argument. E.g.

```
boost::python::object pFun = ...;
MyClass &instance = ...;
pFun(instance); // ... will do all the proper conversion, as long as MyClass is registered.
```

**Comment by tfgsupport** [comment]
Could you kindly point at an example in the Boost.Python tutorials that does this? The examples I've come across so far demonstrate how to expose C++ classes and methods to python and then call these methods from python. The examples I've found of invoking python methods from C++ (google) are all in Python C.

**Comment by tfgsupport** [comment]
Thankyou. That suggestion works. I amended my code to now hold the python file and the python method I retrieve from it in a boost::python::object. I can then invoke the function directly with my class instance.
