### ISSUE TITLE
Replace use of boost type-traits by std type-traits.

### ISSUE THREAD

**Issue by stefanseefeld** [boostorg/python#106]
While this is a good idea in general, this also fixes certain issues (e.g. https://github.com/boostorg/python/issues/105).

This may require some code refactoring, to avoid the code being cluttered with #ifdefs.

**Comment by shreyans800755** [comment]
@stefanseefeld @dabrahams 
I would like to work on this issue.

Just to confirm and get along with contributing method, I need to create PR against `develop` branch, right ?

**Comment by stefanseefeld** [comment]
@shreyans800755 , great ! I'm not aware of anyone else working on this right now, so this would be a great contribution. Please be sure to conditionalize these substitutions to only be active whenever a compiler with the appropriate language support is used. We need to maintain backward compatibility.

I suggest a new `boost/python/detail/type_traits.hpp` header for this.

PRs need to be created against the develop branch.

**Comment by shreyans800755** [comment]
@stefanseefeld 
I'm trying to apply the patch like following:
Adding
```
#if __cplusplus < 201103L
          typename boost::remove_cv<T>::type
#else
          typename std::remove_cv<T>::type
#endif
```
and removing
`typename boost::remove_cv<T>::type`

I don't understand why we need a new file `boost/python/detail/type_traits.hpp`. Can you please explain ? Am I missing something ?

**Comment by stefanseefeld** [comment]
I expect that with the above approach you would end up with lots of locations in the code that would use such a conditional logic, which IMO makes the code hard to read.

Thus what I'd propose is something like:
```
namespace boost { namespace python { namespace detail {
#if __cplusplus < 201103L
  using boost::remove_cv;
  ...
#else
  using std::remove_cv;
  ..
}}} // namespace boost::python::detail
```
such that in the rest of Boost.Python's code you could then simply refer to `boost::python::detail::remove_cv` etc., not having to care which original definition this aliases.
(Note, however, that this is just an idea that I would try out. I haven't actually tested this, and thus could be convinced that it isn't workable. I'd put the conditional above into a new header `boost/python/detail/type_traits.hpp`...)

**Comment by shreyans800755** [comment]
That's wonderful idea. I knew, changes were a bit cumbersome. This sounds like an elegant solution. I'll try to move ahead with this.
