### ISSUE TITLE
Function checked_downcast_impl declared but not defined

### ISSUE THREAD

**Issue by SPKorhonen** [boostorg/python#113]
Header pyobject_type.hpp defines function checked_downcast_impl but it is not defined anywhere as far as I can see. It is used by pyobject_type::checked_downcast, which is further referenced by boost::numpy in header numpy_object_mgr_traits.hpp.

Function checked_downcast_impl should be defined or removed.

**Comment by stefanseefeld** [comment]
This was done in https://github.com/boostorg/python/commit/edd890bd2bdb89ac0d9fbcf5b6ba1dcc0bb66717.
