### ISSUE TITLE
eval(string), exec(string) ignore global, local parameters

### ISSUE THREAD

**Issue by res2k** [boostorg/python#164]
Commit b2f53e1 added new overloads for `eval()` and the various `exec` functions.
However, the backwards compatible `eval(string)` and `exec(string)` methods accepting a `boost::python::string` don't pass through the `global` and `local` args, breaking code that relies on them.
`exec_statement(string)`, `exec_file(string)` are fine.

**Comment by stefanseefeld** [comment]
Fixed with https://github.com/boostorg/python/commit/b09d80a93e299bdaba29b652010b668b87f1306c
