### ISSUE TITLE
Warnings in enum.cpp

### ISSUE THREAD

**Issue by pdimov** [boostorg/python#181]
It looks like the compiler has a point here:
```
libs\python\src\object\enum.cpp(47) : warning C4190: 'auto_free' has C-linkage specified, but returns UDT 'boost::python::api::object' which is incompatible with C
        C:\projects\boost-root\boost/python/object_core.hpp(238) : see declaration of 'boost::python::api::object'
libs\python\src\object\enum.cpp(47) : warning C4930: 'boost::python::api::object auto_free(boost::python::handle<>)': prototyped function not called (was a variable definition intended?)
```

**Comment by stefanseefeld** [comment]
Huh, that's tricky. The compiler in question interprets that line as declaring a function, while what this ought to be is an object definition. So, the warning really hints at a memory leak (as the intent clearly is to create an object that will clean up the `mod` object at end-of-scope).

It seems this line needs to be rewritten, perhaps as "object auto_free = object(handle<>(mod));" ?
I'll work on a patch...

**Comment by pdimov** [comment]
All compilers interpret it that way, but not all of them warn. clang 5, for instance, warns too.

https://travis-ci.org/boostorg/check_build/jobs/317893921#L2311

The easiest fix is to parenthesize it twice, `object auto_free((handle<>(mod)));`.

**Comment by stefanseefeld** [comment]
OK, perhaps, but that spelling looks a bit obscure to me, so I prefer the assignment-operator syntax.

**Comment by pdimov** [comment]
Looks like it could result in an extra copy, although I'm not sure how relevant is this in context.

**Comment by stefanseefeld** [comment]
Nah, the `object a = object(...)` syntax is just a different spelling. There is no extra temporary object involved, at least according to the standard. I can't speak to compiler conformance in general, of course. :-)

**Comment by stefanseefeld** [comment]
Here is the fix: https://github.com/boostorg/python/commit/d6d54ce483c27ef2cddb4d43e6e775c5c496ec62. Let's close this once the warning is gone from the appropriate test runs.

**Comment by pdimov** [comment]
I can confirm that the various MSVCs no longer issue the warning after the fix, in my local tests.

**Comment by stefanseefeld** [comment]
Excellent, thanks.
