### ISSUE TITLE
Boost.Python should be disabled if python headers not present

### ISSUE THREAD

**Issue by djarek** [boostorg/python#194]
Boost.Python should be disabled if python headers are not present in the build environment.

**Comment by stefanseefeld** [comment]
By "disabled" I assume you are referring to `Boost.Build` and its logic to decide which Boost libraries to build. Please submit a feature request there: https://github.com/boostorg/build/issues

**Comment by djarek** [comment]
Yes, that's what I meant. Will create an issue there.
