### ISSUE TITLE
Problems with 64-bit, use (char*)NULL instead of 0

### ISSUE THREAD

**Issue by TheCrazyT** [boostorg/python#198]
Title says it all, the following lines can cause problems:

https://github.com/boostorg/python/blob/28e2c6512cf3878518dff82532650144e849198e/src/object/class.cpp#L621

https://github.com/boostorg/python/blob/28e2c6512cf3878518dff82532650144e849198e/src/object/class.cpp#L631

Its better to use (char*)NULL instead.
I was getting unexpected behavior while execution of an application when i compiled the library with mingw.

**Comment by stefanseefeld** [comment]
Please give some context. What compiler are you using ? And what error are you observing ? Can you produce a minimal self-contained test case for me to reproduce the error ?

**Comment by TheCrazyT** [comment]
Oh well i have made a small example at stackoverflow: 
https://stackoverflow.com/questions/50140750/possible-bug-with-variadic-arguments-on-mingw64-gcc
Basically i first thought its a compiler bug, but it is indeed a bug at the mentioned locations.
The real project that had problems can be found here:
https://github.com/TheCrazyT/roboschool
It used a cross compiled library of boost_python that can be found here:
https://github.com/TheCrazyT/boost_python_build_win
(boost library gets crossbuild by x86_64-w64-mingw32-g++ and uploaded to bintray)
Without the patch file (https://github.com/TheCrazyT/boost_python_build_win/blob/master/add_property.patch) the "roboschool"-project for windows was not executable.

**Comment by stefanseefeld** [comment]
OK, thanks. This is fixed as per https://github.com/boostorg/python/commit/467a89eba794799e5e62a3945f78fd1e0eec506c.
