### ISSUE TITLE
Boost::Python::Numpy library is missing in Windows build

### ISSUE THREAD

**Issue by jzmaddock** [boostorg/python#199]
Moved from https://svn.boost.org/trac10/ticket/13219

**Comment by ndevenish** [comment]
I just had this issue with 1.67 - turns out that the Python installation boost was picking up didn't have `numpy` installed.

**Comment by stefanseefeld** [comment]
@ndevenish , can you confirm that rebuilding with `numpy` installed will actually solve this issue ? That would allow me to close this issue. Thanks !

**Comment by ndevenish** [comment]
Yes, after installing numpy onto the python boost was looking at, the library got created and installed.

I had to pass `--debug-configuration` to `b2` to actually see the test it was making, which might be useful to anyone having this problem in the future.

**Comment by stefanseefeld** [comment]
Good point.
Thanks for checking !
