### ISSUE TITLE
Numpy integration?

### ISSUE THREAD

**Issue by mdboom** [boostorg/python#26]
I'm the author of "numpy-boost", a library to allow access to Numpy arrays through the boost::multi_array interface, as well as integration with the type converters in boost::python.

See http://github.com/mdboom/numpy-boost

Would there be interest in a pull request to add this functionality to boost::python?

Are there contributing guidelines available?

**Comment by nevion** [comment]
+1, let's axe the old ndarray support and get this in where it belongs.

**Comment by stefanseefeld** [comment]
We have been working on NumPy integration in a separate project: https://github.com/ndarray/Boost.NumPy, which I intend to merge into Boost.Python eventually (hopefully soon).

**Comment by stefanseefeld** [comment]
Since the original issue here was about a separate NumPy binding, I'm going to close this. As I mentioned earlier, integration of an existing NumPy extension is well underway, so this is what we will focus on in the short term.
Thanks,
