### ISSUE TITLE
 error: use of deleted function

### ISSUE THREAD

**Issue by mahuichao** [boostorg/python#272]
I have a class **PhoneExtractor**,the header file like:
`class PhoneExtractor{
        public:
                PhoneExtractor(){}
                PhoneExtractor(string conf_file_name);
                //PhoneExtractor();
                ~PhoneExtractor();
}`
I use boost python,the file like:
`using namespace boost::python;

BOOST_PYTHON_MODULE(libextractor)
{
        class_<PhoneExtractor>("PhoneExtractor",init<std::string>())
        .def("chainDecode", &PhoneExtractor::chainDecode)
        ;
}`

But I got error:

> /home/mahch/workspace/dep/lib/include/boost/python/object/value_holder.hpp:133:13: error: use of deleted function ‘PhoneExtractor::PhoneExtractor(const PhoneExtractor&)’
             BOOST_PP_REPEAT_1ST(N, BOOST_PYTHON_UNFORWARD_LOCAL, nil)

I don't know where I am wrong,can you help me ?

**Comment by eugene-kulak** [comment]
@mclow what happened to this issue? how people facing the same problem will find what to do?

**Comment by stefanseefeld** [comment]
The code snippet above is ill-formatted and incomplete. Could you please re-post it with the correct spelling / formatting, so I don't have to second-guess what you are trying to do ?
