### ISSUE TITLE
Handling errors inside BOOST_PYTHON_MODULE()

### ISSUE THREAD

**Issue by db4** [boostorg/python#280]
I have a module that may fail to initialize due to missing dependencies. So I do
```c++
BOOST_PYTHON_MODULE(mymodule)
{
...
    if (missing_dependency) {
        throw std::exception("Missing dependency");
    }
...
}
```
The exception is correctly caught and `PyErr_SetString(PyExc_RuntimeError, x.what())` is called, but python reports
```
    import mymodule
SystemError: initialization of mymodule raised unreported exception
```
Why `unreported exception`? My platform is Windows 10/Python 3.7.4 x64/MSVC 2017 if that matters. python_boost version is 1.69.0.

**Comment by stefanseefeld** [comment]
What happens if you replace `std::exception` by `std::runtime_error` or some other more specific exception type ?

**Comment by db4** [comment]
No, switching to `std::runtime_error` does not help, I still have `unreported exception`. And looks like the exception type has nothing to do with the issue: I set a debug breakpoint in
https://github.com/boostorg/python/blob/ac62db1cf17c0af44dc2b2117f9ddeee327e5e7c/src/errors.cpp#L48-L51
and verified that this catch case was executed.

**Comment by stefanseefeld** [comment]
OK, I see. So the Python error has correctly been set by Boost.Python, but Python's own runtime then flags this as an "unreported exception". In other words, you could strip your code off all Boost.Python references, only using Python's own C API, and you'd still observe the issue.
Can you report this to the Python bug tracker ?

**Comment by db4** [comment]
Are you sure that's a Python problem? Maybe
https://github.com/boostorg/python/blob/1727b67a5a92c8c3564d4ee244fffd758e54d7cc/src/module.cpp#L24
should be replaced with
```c++
if (handle_exception(init_function)) return NULL;
```
?

**Comment by stefanseefeld** [comment]
Oh, indeed, that looks sensible. Can you write a (minimal) test case to demonstrate the problem as well as that your proposed change fixes it ? That would make a great PR !

**Comment by db4** [comment]
I just tried to fix it locally this way and it solved the problem. Well, I could try to create a test case and PR, but I'm quite new to boost libs testing infrastructure...

**Comment by stefanseefeld** [comment]
OK, great. I'll see whether I can write a quick test.

**Comment by db4** [comment]
Hi @stefanseefeld
Any news on the issue? Are you still planning to create a test and finally commit the fix?

**Comment by tdelame** [comment]
Had the same issue, boost::python was hiding the real exception with `raised unreported exception`. I applied the patch `if (handle_exception(init_function)) return NULL;` mentioned by @db4 and now the real exception is thrown.

**Comment by twvd** [comment]
Also just ran into this problem.. Just bumping this issue to show it's still relevant and affects users.

**Comment by db4** [comment]
> Also just ran into this problem.. Just bumping this issue to show it's still relevant and affects users.

I finally decided to stop waiting for something and create PR myself
