### ISSUE TITLE
`import("__main__")` crashes on Windows in Debug mode

### ISSUE THREAD

**Issue by stephengtuggy** [boostorg/python#405]
As reported [here](https://stackoverflow.com/questions/24986361/boost-python-on-windows-crashes-at-import-main):

Running `boost::python::import("__main__");` crashes on Windows, specifically when compiled in Debug configuration (not Release). This was on Windows 11 x64, with Python 3.10, I believe. Others have reported the same issue with other versions of Windows and of Python. This issue does not exist on Linux, as far as I can tell.

A small program illustrating this bug can be found [here](https://github.com/stephengtuggy/PyPoc/blob/main/main.cpp).

Thanks.

**Comment by Osyotr** [comment]
@stephengtuggy you might need to add
```cmake
target_compile_definitions(${target_name} PUBLIC "$<$<CONFIG:Debug>:BOOST_DEBUG_PYTHON>")
target_compile_definitions(${target_name} PUBLIC "$<$<CONFIG:Debug>:Py_DEBUG>")
```
to your `CMakeLists.txt`.

**Comment by stephengtuggy** [comment]
> @stephengtuggy you might need to add
> 
> ```cmake
> target_compile_definitions(${target_name} PUBLIC "$<$<CONFIG:Debug>:BOOST_DEBUG_PYTHON>")
> target_compile_definitions(${target_name} PUBLIC "$<$<CONFIG:Debug>:Py_DEBUG>")
> ```
> 
> to your `CMakeLists.txt`.

@Osyotr Hmm. Interesting. When I make those changes, I am no longer able to reproduce the crash. At least not as reliably.

Any idea what makes the difference?

**Comment by Osyotr** [comment]
ABI incompatibility.
https://www.boost.org/doc/libs/1_81_0/libs/python/doc/html/building/python_debugging_builds.html

**Comment by stephengtuggy** [comment]
I see. I had `BOOST_DEBUG_PYTHON` in place, but not `Py_DEBUG`. Also, I was setting the compile definitions on the directory level, not per-target. Not sure if the latter makes a significant difference or not.

**Comment by stephengtuggy** [comment]
Closing, since @Osyotr 's solution worked. Thanks!

**Comment by stephengtuggy** [comment]
@Osyotr I linked your solution in my answer to my own StackOverflow question, here: https://stackoverflow.com/a/79270374/5067822

Thanks again!
