### ISSUE TITLE
Compilation failure using numpy 2.0.0b1

### ISSUE THREAD

**Issue by duburcqa** [boostorg/python#431]
I tried to compile Boost::Python 1.84 library against `numpy==2.0.0b1`, but I'm getting a compilation error:
```
libs/python/src/numpy/dtype.cpp:101:83: error: no member named 'elsize' in '_PyArray_Descr'
int dtype::get_itemsize() const { return reinterpret_cast<PyArray_Descr*>(ptr())->elsize;}
```

**Comment by duburcqa** [comment]
See related part of numpy documentation: https://numpy.org/devdocs/release/2.0.0-notes.html#descriptor-elsize-and-alignment-access

**Comment by jakirkham** [comment]
Was this fixed with PR ( https://github.com/boostorg/python/pull/432 )?

**Comment by duburcqa** [comment]
Yes. Closing.

**Comment by jakirkham** [comment]
Thanks Alexis! 🙏

**Comment by jakobandersen** [comment]
While fixed now, it doesn't seem possible to build any prior Boost release if NumPy 2.x is installed. Is it possible to disable just the NumPy part when building via the central ``b2``?

**Comment by jakirkham** [comment]
[Boost 1.86.0]( https://www.boost.org/users/history/version_1_86_0.html ) got released just a few days ago. Did this not make it in there?

**Comment by jakobandersen** [comment]
> [Boost 1.86.0](https://www.boost.org/users/history/version_1_86_0.html) got released just a few days ago. Did this not make it in there?

It doesn't look like it :-(

**Comment by jakirkham** [comment]
@stefanseefeld what do we need to do to get this in the next Boost release? Is 1.86.1 an option?
