### ISSUE TITLE
Bug with OpenMP and python 3.12

### ISSUE THREAD

**Issue by efp** [boostorg/python#457]
Greetings. There is a problem using boost python with python 3.12 and OpenMP, surely related to this: [https://stackoverflow.com/questions/78200321/python3-12-c-api-segfaults-with-openmp](https://stackoverflow.com/questions/78200321/python3-12-c-api-segfaults-with-openmp)

The following program works fine with python 3.6, but segfaults with 3.12:

```
#include <boost/python.hpp>
#include <Python.h>
#include <omp.h>

#include <iostream>

int main(int argc, char* argv[])
{
    Py_Initialize() ;

    namespace bp = boost::python ;

    const auto max_threads = omp_get_max_threads() ;
    std::cout << "threads: " << max_threads << std::endl ;

    bp::object x ;

    #pragma omp parallel for
    for (int i=0; i<100; ++i)
    { 
        #pragma omp critical
        x = bp::eval("1 + 1") ;
    }

    std::cout << "1 + 1 is " << bp::extract<int>(x) << std::endl ;
}
```

It will also work fine in 3.12 if you comment out the parallel directive.

**Comment by efp** [comment]
As I understand it, it's not an issue with the C API, it's an issue with not correctly using the GIL, which did not cause problems until 3.12.

**Comment by stefanseefeld** [comment]
Oh, indeed, the GIL ! :-)
Yes, so your code snippet above is not thread-safe. You should acquire the GIL within the for-loop prior to running `eval`, to serialize access to the Python runtime.

E.g.

`struct gil_lock
{
  gil_lock() : state(PyGILState_Ensure()) {}
  ~gil_lock() { PyGILState_Release(state);}
  PyGILState_STATE state;
};

struct gil_unlock
{
  gil_unlock() : save(PyEval_SaveThread()) {}
  ~gil_unlock() { PyEval_RestoreThread(save);}
  PyThreadState *save;
};

...
gil_unlock unlock;
#pragma omp parallel for
for (int i=0; i<100; ++i)
{
    gil_lock lock;
    #pragma omp critical
    x = bp::eval("1 + 1") ;
}

`

**Comment by efp** [comment]
Thanks for the reply... I would have thought boost python (bp) would acquire & release the GIL around all of the C API function calls itself, otherwise one would have to do it around virtually all bp calls, and we shouldn't have to mix bp & the C API. 

Prior to python 3.12 it seems the omp critical section was enough to make it thread safe. Now something about the per-thread python interpreter state is causing problems. In theory the PyGILState_Ensure() and PyGILState_Release() statements should take care of that, even though it seems redundant with the critical block. I suppose using the GIL lock we should be able to do away with the critical block.

But, your solution still segfaults; I've done more experiments and they also all segfault, so maybe there is a lower level problem. Still experimenting...

**Comment by stefanseefeld** [comment]
The whole point of the GIL is to reduce the need to acquire & release on a fine-grained level as that would kill performance. That is, locking is something done only as needed. Still, I get your point, Boost.Python could at least provide some more convenient API, including call-policies to indicate whether or not a call should perform any such lock acquisition / release.
I wonder how this whole thing is going to evolve as with Python 3.13 the GIL is optional. We shall see...

**Comment by efp** [comment]
So, to close this out: it appears what prevented your solution from working was my final 

`std::cout << "1 + 1 is " << bp::extract<int>(x) << std::endl ;`

We had to restore the original thread state before doing that, as 'x' was declared outside the parallel section. So I just needed to enclose your gil_unlock in a scope. 

Thanks, and cheers.
