### ISSUE TITLE
'pyconfig.h': No such file or directory

### ISSUE THREAD

**Issue by OlafvdSpek** [boostorg/python#68]
Boost 1.61 @ VS2015:

`    call "C:\Users\Olaf\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86.cmd" >nul
cl /Zm800 -nologo @"bin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi\exec.obj.rsp"

...failed compile-c-c++ bin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi\exec.obj...
compile-c-c++ bin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi\object\function_doc_signature.obj
function_doc_signature.cpp
C:\VC\boost\boost/python/detail/wrap_python.hpp(50): fatal error C1083: Cannot open include file: 'pyconfig.h': No such file or directory

```
call "C:\Users\Olaf\AppData\Local\Temp\b2_msvc_14.0_vcvarsall_x86.cmd" >nul
```

cl /Zm800 -nologo @"bin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi\object\function_doc_signature.obj.rsp"

...failed compile-c-c++ bin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi\object\function_doc_signature.obj...
...skipped <pbin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi>libboost_python-vc140-mt-gd-1_61.lib for lack of <pbin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi>numeric.obj...
...skipped <pstage\lib>libboost_python-vc140-mt-gd-1_61.lib for lack of <pbin.v2\libs\python\build\msvc-14.0\debug\link-static\threading-multi>libboost_python-vc140-mt-gd-1_61.lib...
...failed updating 56 targets...
...skipped 4 targets...`

**Comment by stefanseefeld** [comment]
It's hard to tell what exactly goes wrong, but it seems clear that the problem is that Python itself (specifically, its main header file) isn't found. Make sure you configure your build correctly by indicating the path to your Python installation.

**Comment by macheeto** [comment]
This problem is also tracked here:
https://svn.boost.org/trac10/ticket/11120#comment:21
There are useful hints in that ticket.

**Comment by OlafvdSpek** [comment]
> Make sure you configure your build correctly by indicating the path to your Python installation.

Python isn't installed.. 
I guess it's a problem in the Python detection code that has since been solved.
