### ISSUE TITLE
Deprecate use of std::auto_ptr in favour of std::unique_ptr

### ISSUE THREAD

**Issue by stefanseefeld** [boostorg/python#80]
Replace all **internal** usages of `std::auto_ptr` by `std::unique_ptr` whenever the compiler supports it. Support for `std::auto_ptr` in user code needs to be maintained for backward-compatibility.

**Comment by stefanseefeld** [comment]
This is addressed in https://github.com/boostorg/python/commit/5029273ca8e6c18bfc3894de0cc3011f091988f6.

**Comment by meshula** [comment]
Visual Studio 2017 in c++ latest mode fully removes auto_ptr. The fix referenced in this issue has never worked on Visual Studio, as __cplusplus is defined as 199711 irrespective of settings.

Unless I'm missing something I'm supposed to do, but can't find, in Visual Studio, this patch doesn't seem valid for MSVC.

https://connect.microsoft.com/VisualStudio/feedback/details/763051/a-value-of-predefined-macro-cplusplus-is-still-199711l

I appreciate that Microsoft should fix their stuff, but perhaps there could be a different fix here in the mean time, such as checking __cplusplus on compilers that support it properly like clang and gcc, but checking _MSC_VER on msvc.
