### ISSUE TITLE
Documentation link on the official site is broken

### ISSUE THREAD

**Issue by vasily-v-ryabov** [boostorg/python#84]
On [Getting Started Guide for Windows](http://www.boost.org/doc/libs/1_61_0/more/getting_started/windows.html) go to paragraph 3 and follow the link to [Boost.Python](http://www.boost.org/doc/libs/1_61_0/libs/python/doc/building.html) that shows the following message:

```
404 Not Found

File "/home/www/shared/archives/live/boost_1_61_0/libs/python/doc/building.html" not found.

Unable to find file.
```

**Comment by stefanseefeld** [comment]
The page containing the wrong link (http://www.boost.org/doc/libs/1_61_0/more/getting_started/windows.html) doesn't belong to Boost.Python. I'm not sure what module owns that, probably https://github.com/boostorg/website.
