### ISSUE TITLE
tests for python3 - what about to remove useless dependence on 'past.builtins' ?

### ISSUE THREAD

**Issue by vmurashev** [boostorg/python#87]
Rationale:
'past.builtins' is not a part of stock python modules, as result it's difficult to run boost-python tests in limited environments (like Android) at the same time it is the one line only to fix it -
Code like
if (sys.version_info.major >= 3):
    from past.builtins import long

Can be easily replaced with:
if (sys.version_info.major >= 3):
    long = int

**Comment by vmurashev** [comment]
patch suggested - see pull request 88

**Comment by stefanseefeld** [comment]
Much simpler indeed. Merged, thanks !
