### ISSUE TITLE
Building on Windows does not create shared Boost.Numpy

### ISSUE THREAD

**Issue by dolfim** [boostorg/python#98]
At conda-forge/boost-feedstock#32 we are trying to finalize the Boost Python package on Conda.
The build currently fails while copying ```boost_numpy-vc90-mt-1_63.lib```, because the file does not exist.

The full log is at: boost_numpy-vc90-mt-1_63.lib
The build command is:
```batch
.\b2 install ^
    --build-dir=buildboost ^
    --prefix=%LIBRARY_PREFIX% ^
    toolset=msvc-%VS_MAJOR%.0 ^
    address-model=%ARCH% ^
    variant=release ^
    threading=multi ^
    link=static,shared ^
    --with-python ^
    -j%CPU_COUNT%
```

Is there something wrong in the build process, or did we find an issue in the Boost building process?

**Comment by jakirkham** [comment]
I think the link to the log got lost. Linked below.

Note: This seems to happen with all Boost.Python builds on Windows, but not on Unix.

ref: https://ci.appveyor.com/project/conda-forge/boost-feedstock/build/1.0.97

**Comment by jakirkham** [comment]
Any help on this would be greatly appreciated. We're kind of at a loss ATM.

**Comment by jhunold** [comment]
It is the other way round. Building the shared libraries fails as the missing `lib`-prefix indicates the shared library. This is no wonder as the necessary dllexport/-import magic is completely missing from Boost.Numpy. The msvc thus refuses to create the empty `boost_numpy-vc90-mt-1_63.lib' stub which is needed by the `install`routine.

**Comment by jakirkham** [comment]
Yeah, sorry, we just realized we had it backwards earlier.

So what sort of change would we be looking at?

**Comment by XWarin** [comment]
Hi !

I stumbled on that issue yesterday  trying to get rid of the old (independent) boost numpy.
Is this there something scheduled to correct this dynamic link problem ?
Best regards

**Comment by SPKorhonen** [comment]
I also stumbled onto this problem when trying to update boost to 1.63 to get rid of separate boost::numpy dependency. 

The problem is that, at least on windows, numpy generates empty shared libraries (the dll is generated but exports no symbols). This is due to the windows dll default settings. Everything that is not explicitly exported is private. As @jhunold stated the numpy is missing dllexport/-import magic words. I think that liberal sprinkling of BOOST_PYTHON_DECL before all symbols that are to be exported would help.

**Comment by SPKorhonen** [comment]
I could make an effort on fixing this issue if nobody else has free time to devote to resolving this...

**Comment by XWarin** [comment]
Hi

It would be a good idea. I don't use much windows and i only port my work from linux.
Right now when on windows i still recompile the old  boost numpy.
Best regards

**Comment by jakirkham** [comment]
Seconding @XWarin. Some of us have limited knowledge of building on Windows and/or time to devote to this. As it sounds like you have both knowledge and time, @SPKorhonen, I'd say go for it. We would be very appreciative. Can help test patches if you would like.

**Comment by stefanseefeld** [comment]
I have just pusted a PR at https://github.com/boostorg/python/pull/108 in an attempt to fix this. I'd appreciate if someone could confirm, before I merge.

**Comment by jakirkham** [comment]
So I guess this should be fixed by PR ( https://github.com/boostorg/python/pull/110 ). Will try to test this and let you know how it goes.

**Comment by dolfim** [comment]
We added the patch to the conda-forge package. Now it will try building here: https://ci.appveyor.com/project/conda-forge/boost-feedstock/build/1.0.109

Thanks a lot for the patch.

**Comment by dolfim** [comment]
It seems to work correctly!

**Comment by XWarin** [comment]
Thank you very much !

2017-02-16 7:17 GMT+01:00 Michele Dolfi <notifications@github.com>:
